Task#87 added pickup_choose_screen and onboarding_screen
netos23/the_shop pull request #37
Opened 2023-05-22 15:42 UTC by LordOfTheApples123

2023-05-22 21:13 UTC, netos23 requested changes

2023-05-23 07:24 UTC, LordOfTheApples123 commented
добавил git ignore, переименовал buttons, добавил expanded

2023-05-23 15:08 UTC, netos23 requested changes

2023-06-03 23:05 UTC, netos23 approved these changes

2023-06-03 23:05 UTC, merged