Task#91
netos23/the_shop pull request #39
Opened 2023-06-03 21:15 UTC by LordOfTheApples123

2023-06-03 23:02 UTC, netos23 requested changes

2023-06-03 23:02 UTC, netos23 commented on mobile_app/the_store_app/lib/screens/starting_screen/starting_method_screen/starting_method_screen_widget.dart
> +              lightColor: wm.colorScheme.onPrimary,
не исспользуй этот конструктор за исключением случаев когда нужны паденги со всех сторон 
предпочтительно symetriс или only

2023-06-03 23:02 UTC, netos23 commented on mobile_app/the_store_app/lib/screens/starting_screen/onboarding_screen/onboarding_screen_widget.dart
> +    final PageController controller = PageController();
контроллер не создают в билде он должен быть в wm

2023-06-04 09:54 UTC, LordOfTheApples123 commented
fix attempt

2023-06-04 09:55 UTC, LordOfTheApples123 commented
какой-то косяк пропертис из гит игнора вылезли

2023-06-05 12:31 UTC, merged